pipeline:
  name: cd1
  identifier: cd1
  projectIdentifier: RISHI_TEST_REMOTE
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cd1
        identifier: cd1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: env1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra1
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "HI"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          services:
            values:
              - serviceRef: svc1
              - serviceRef: svc1
            metadata:
              parallel: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
